replicaCount: 1

image1:
  repository: mohammedyunus2002/result
  pullPolicy: IfNotPresent
  tag: "12276974490"

image2:
  repository: mohammedyunus2002/vote
  pullPolicy: IfNotPresent
  tag: "12277013643"

image3:
  repository: mohammedyunus2002/worker
  pullPolicy: IfNotPresent
  tag: "12277054216"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: challenge.yunus.in
  path: /
  services:
    vote: vote     
    result: result 
  ports:
    vote: 8080     
    result: 8081   



resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http