apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  annotations:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /vote
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.services.vote }}
                port:
                  number: {{ .Values.ingress.ports.vote }}
          - path: /result
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.services.result }}
                port:
                  number: {{ .Values.ingress.ports.result }}
