name: Build Worker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'

jobs:
  build-and-push:

    name: Build and Push Worker Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed to push docker image to ghcr.io
      pull-requests: write # Needed to create and update comments in PRs

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 6: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 8: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: worker
          file: worker/Dockerfile
          push: true
          tags: mohammedyunus2002/worker:latest
          mohammedyunus2002/worker:${{ github.run_id }}
          platforms: linux/arm64

  update-helm-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
        
    - name: Update tag in Helm chart
      run: |
        sed -i "/image3:/,/tag:/ s/tag: \".*\"/tag: \"${{ github.run_id }}\"/" helm-microservices/values.yaml
        
    - name: Commit and push changes
      run: |
        git config --global user.email "shaikhyunus.ys89@gmail.com"
        git config --global user.name "Mohammed Yunus"
        git add helm-microservices/values.yaml
        git commit -m "Update tag in Helm chart [skip ci]"
        git push