name: Build Vote

on:
  push:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'

jobs:
  build-and-push:
    name: Vote Call Docker Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed to push docker image to ghcr.io
      pull-requests: write # Needed to create and update comments in PRs

    steps:
      # Step 1: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 4: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run tests with pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Step 7: Run code quality check with Flake8
      - name: Run code quality check with Flake8
        run: |
          pip install flake8
          flake8 vote/

      # Step 8: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 9: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: vote
          file: vote/Dockerfile
          push: true
          tags: |
            mohammedyunus2002/vote:latest
          platforms: linux/amd64,linux/arm64/v8
