name: Build Worker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'worker/**'
      - '.github/workflows/build-worker.yaml'

jobs:
  build-and-push:

    name: Build and Push Worker Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed to push docker image to ghcr.io
      pull-requests: write # Needed to create and update comments in PRs

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      # Step 3: Install dependencies and restore
      - name: Restore dependencies
        run: dotnet restore worker/worker.csproj

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build worker/worker.csproj --configuration Release

      # Step 5: Run tests (optional, if tests are set up)
      - name: Run tests
        run: dotnet test worker/worker.csproj

      # Step 6: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 8: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: worker
          file: worker/Dockerfile
          push: true
          tags: mohammedyunus2002/worker:latest
          platforms: linux/arm64
