name: Build Vote

on:
  push:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'vote/**'
      - '.github/workflows/call-docker-build-vote.yaml'

jobs:
  build-and-push:
    name: Vote Call Docker Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Needed to push docker image to ghcr.io
      pull-requests: write # Needed to create and update comments in PRs

    steps:
      # Step 1: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 8: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 9: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: vote
          file: vote/Dockerfile
          push: true
          tags: |
            mohammedyunus2002/vote:latest
          platforms: linux/amd64,linux/arm64/v8
          
  update-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
        
    - name: Update tag in Helm chart
      run: |
        sed -i "/image2:/,/tag:/ s/tag: \".*\"/tag: \"${{ github.run_id }}\"/" helm-microservices/values.yaml
        
    - name: Commit and push changes
      run: |
        git config --global user.email "shaikhyunus.ys89@gmail.com"
        git config --global user.name "Mohammed Yunus"
        git add helm-microservices/values.yaml
        git commit -m "Update tag in Helm chart [skip ci]"
        git push